### ISSUE TITLE
So change the seeder and the problems go away?

### ISSUE THREAD

**Issue by firepacket** [Sc00bz/break-uheprng#2]
breakuheprng.html fails as soon as you change the random seed rounds from 48 to anything else.

Why haven't your other biases been discovered elsewhere?

He claims the generator has 1,678 bits of entropy. Do the biases still exist when you change the seed input rounds?

**Comment by firepacket** [comment]
These all appear to be fixable problems.

**Comment by firepacket** [comment]
Does it still pass dieharder if the random initialization is fixed?

**Comment by Sc00bz** [comment]
> breakuheprng.html fails as soon as you change the random seed rounds from 48 to anything else.

The attack code is built for 48. If you also changed every `48` in the attack code to match the "seed rounds" it will likely still work. I'd have to check but it looks like every number based off that uses that number (eg `2*48+2`). Pretty sure the attack code assumes even just like UHEPRNG does.

> Why haven't your other biases been discovered elsewhere?

I don't know. Maybe it's that the biases are small and can only easily be found by reading the code which no one really does.

> He claims the generator has 1,678 bits of entropy. Do the biases still exist when you change the seed input rounds?

You mean 1,536 bits. Yes, the bias comes from the magic number 1768863.

> These all appear to be fixable problems.

No they aren't. Unless you mean rewrite the whole thing so it's a CSPRNG.

> Does it still pass dieharder if the random initialization is fixed?

Probably but so does this and this is also not a CSPRNG:

    state = sha256(state);
    return state;

**Comment by firepacket** [comment]
> You mean 1,536 bits. Yes, the bias comes from the magic number 1768863.
He claim's it's 1678 bits.

[https://www.grc.com/otg/uheprng.htm](https://www.grc.com/otg/uheprng.html)
> “SeedKey” uses the 94 printable ASCII characters (spaces are ignored). Therefore, this yields 94256 possible seedkeys. This is 1.32 x 10505 possible strings, which is equivalent to **1,678 bits of entropy**.

Would you mind going into more detail as to why this logic is wrong?

> The attack code is built for 48. If you also changed every 48 in the attack code to match the "seed rounds" it will likely still work. I'd have to check but it looks like every number based off that uses that number (eg 2*48+2). Pretty sure the attack code assumes even just like UHEPRNG does.

Obviously, if you know the starting state of any PRNG you will be able to predict its values, right? Can this be fixed by simply initializing s[] with Mash() from a number from a RNGCryptoProvider, would that make it "cryptographically secure" from that point on?

I noticed it takes a few rounds of hashing before it reaches maximum shannon entropy of 6.55401181 - Isn't that pretty good for ASCII text? I even built a little histogram analyze the results and I do notice slight biases but they don't seem to stay consistent.

My Mash code looks like this:

`double Mash(string data)`
`        {`
`            string x = data == null ? "" : data.ToString();`
`            uint n = 0xefc8249d;`
`            double h;`
`            if (!string.IsNullOrEmpty(x))`
`            {`
`                while (x.Length > 0)`
`                {`
`                    n += Convert.ToUInt32(x[ 0 ]);`
 `                   x = x.Remove(0, 1);`
 `                   h = 0.02519603282416938 * n;`
`                    n = (uint)h;`
`                    h -= n;`
`                    h *= n;`
`                    n = (uint)h;`
`                    h -= n;`
`                    n += (uint)h * unchecked((uint)0x100000000);`
`                }`
`                return n * 2.3283064365386963e-10; // 2^-32`
`            }`
`            else`
`                return n;`
`        }`
Do I still need to move the return statement? Are there any other problems with this code?
Am I ruining it by using (uint)h? Is there another method to get this into c#?

**Comment by firepacket** [comment]
In my implementation there is a heavy bias for the first number 33 (!). Do you know what's causing this? How do I get rid of it? After about 200,000 characters it goes away but at the beginning it is very strong bias for this one character.

**Comment by Sc00bz** [comment]
> > You mean 1,536 bits. Yes, the bias comes from the magic number 1768863.
> > He claim's it's 1678 bits.
> 
> [https://www.grc.com/otg/uheprng.htm](https://www.grc.com/otg/uheprng.html)
> 
> > “SeedKey” uses the 94 printable ASCII characters (spaces are ignored). Therefore, this yields 94256 possible seedkeys. This is 1.32 x 10505 possible strings, which is equivalent to **1,678 bits of entropy**.
> 
> Would you mind going into more detail as to why this logic is wrong?

The next sentence is "Since this is greater than the total entropic state of the UHEPRNG, a SeedKey of this length and complexity is sufficient (and necessary) to fully initialize a PRNG of this complexity."

This is saying 1,678 bits > 1,536 bits therefore 1,678 bits can "fully" seed the 1,536 bits of internal state.

> > The attack code is built for 48. If you also changed every 48 in the attack code to match the "seed rounds" it will likely still work. I'd have to check but it looks like every number based off that uses that number (eg 2*48+2). Pretty sure the attack code assumes even just like UHEPRNG does.
> 
> Obviously, if you know the starting state of any PRNG you will be able to predict its values, right? Can this be fixed by simply initializing s[] with Mash() from a number from a RNGCryptoProvider, would that make it "cryptographically secure" from that point on?

You keep saying this thing about "knowing the starting state". I do not know the starting state. I ask for random numbers and build the state from that. This PRNG is returning its internal state. I record that data and can predict future output.

> I noticed it takes a few rounds of hashing before it reaches maximum shannon entropy of 6.55401181 - Isn't that pretty good for ASCII text? I even built a little histogram analyze the results and I do notice slight biases but they don't seem to stay consistent.
> 
> My Mash code looks like this:
> 
> `double Mash(string data)`
> ` {`
> ` string x = data == null ? "" : data.ToString();`
> ` uint n = 0xefc8249d;`
> ` double h;`
> ` if (!string.IsNullOrEmpty(x))`
> ` {`
> ` while (x.Length > 0)`
> ` {`
> ` n += Convert.ToUInt32(x[ 0 ]);`
> ` x = x.Remove(0, 1);`
> ` h = 0.02519603282416938 * n;`
> ` n = (uint)h;`
> ` h -= n;`
> ` h *= n;`
> ` n = (uint)h;`
> ` h -= n;`
> ` n += (uint)h * unchecked((uint)0x100000000);`
> ` }`
> ` return n * 2.3283064365386963e-10; // 2^-32`
> ` }`
> ` else`
> ` return n;`
> ` }`
> Do I still need to move the return statement? Are there any other problems with this code?
> Am I ruining it by using (uint)h? Is there another method to get this into c#?

Quickie code review: there are at least 3 things broken in your code. Conclusion use a real CSPRNG that you did not write. Also take [Dan Boneh's crypto class](https://crypto.stanford.edu/~dabo/courses/OnlineCrypto/). Oh it starts today... hmm it might always be "starting today" or a huge coincidence.

**Comment by firepacket** [comment]
> Quickie code review: there are at least 3 things broken in your code. Conclusion use a real CSPRNG that you did not write. Also take Dan Boneh's crypto class. Oh it starts today... hmm it might always be "starting today" or a huge coincidence.

Yet you make no attempt to direct attention to them?

> hmm it might always be "starting today" or a huge coincidence.

humor

**Comment by Sc00bz** [comment]
> Yet you make no attempt to direct attention to them?

Yeah otherwise you'd fix them then claim it's a CSPRNG, but if you know it's buggy then you won't use it. I found another bug. Wait it's 2 bugs on the same line. So here's the most obvious one:

```
-        return n * 2.3283064365386963e-10; // 2^-32
     }
-    else
-        return n;
+    return n * 2.3283064365386963e-10; // 2^-32
}
```

It's still a broken implementation of a PRNG that claims to be a CSPRNG. Please do not use this when security matters.

**Comment by firepacket** [comment]
Sure, I'm just studying the differences between the two, is that allowed? And what if you don't have access to an CSPRNG like was the case when this was written?

The fact that you think withholding information to manipulate my behavior is better than just explaining yourself is highly questionable ethically and functionally.

>+    return n * 2.3283064365386963e-10; // 2^-32

That's the same correction you mentioned earlier. Is there anything specific to my other changes?

Does Mash() give up its state or does that happen elsewhere? IF a CSPRNG is used to initialize s[] do the problems still exist? If so why, and where?

**Comment by firepacket** [comment]
> state = sha256(state);
> return state;

Why is that not a CSPRNG? Sha256 is used for randomness all the time.

**Comment by Sc00bz** [comment]
OK I fixed everything that I found wrong in this one function vs the original. Note neither function is cryptographic and should not be used when cryptography is needed. Also `Mash()` needs to keep the previous `n` value for the next call. In other languages you can use the keyword `static` but not in C#. If this is in a class you could add a private variable for this. You'll want to load it and then save it at the end before returning because of pointers and it's less bad with threads if you don't use a mutex.

```
double Mash(string data)
{
    static uint n = 0xefc8249d; // Oh that's not a thing. I do not know C#
                                // you'll need to figure this out. Also this
                                // will cause problems with threads. So use
                                // a mutex or a lock on this whole function.
    double h;
    if (!string.IsNullOrEmpty(data))
    {
        for (int i = 0; i < data.Length; i++)
        {
            n += Convert.ToUInt32(data[ i ]);
            h = 0.02519603282416938 * n;
            n = (uint)h;
            h -= n;
            h *= n;
            n = (uint)h;
            h -= n;
            n += (uint) (h * 4294967296.0);
        }
    }
    else
        n = 0xefc8249d;
    return n * 2.3283064365386963e-10; // 2^-32
}
```

Here's a diff:
```
  double Mash(string data)
  {
-     string x = data == null ? "" : data.ToString();
-     uint n = 0xefc8249d;
+     static uint n = 0xefc8249d; // Oh that's not a thing. I do not know C#
+                                 // you'll need to figure this out. Also this
+                                 // will cause problems with threads. So use
+                                 // a mutex or a lock on this whole function.
      double h;
-     if (!string.IsNullOrEmpty(x))
+     if (!string.IsNullOrEmpty(data))
      {
-         while (x.Length > 0)
+         for (int i = 0; i < data.Length; i++)
          {
-             n += Convert.ToUInt32(x[ 0 ]);
+             n += Convert.ToUInt32(data[ i ]);
-             x = x.Remove(0, 1);
              h = 0.02519603282416938 * n;
              n = (uint)h;
              h -= n;
              h *= n;
              n = (uint)h;
              h -= n;
-             n += (uint)h * unchecked((uint)0x100000000);
+             n += (uint) (h * 4294967296.0);
          }
-         return n * 2.3283064365386963e-10; // 2^-32
      }
      else
+         n = 0xefc8249d;
-         return n;
+     return n * 2.3283064365386963e-10; // 2^-32
  }
```

> And what if you don't have access to an CSPRNG like was the case when this was written?

Exit or keep trying. [C# has a built in one so you don't have to worry](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?view=net-5.0). Yes, I know it can throw an exception "The cryptographic service provider (CSP) cannot be acquired." This will never happen and if it does then exit or try again, but it doesn't matter because the computer is about to blue screen anyway.

> Does Mash() give up its state or does that happen elsewhere?

Elsewhere. `Mash()` just converts the seed into the state.

> IF a CSPRNG is used to initialize s[] do the problems still exist? If so why, and where?

Yes. There are no cryptographic functions used and it returns its internal state. Everywhere, literally every line of code.

> > state = sha256(state);
> > return state;
>
> Why is that not a CSPRNG?

It returns the state of the PRNG.

These do not return the state:
```
state++;
return sha256(state);
```
or
```
state = sha256(state);
return sha256(state || "0");
```
The first is better because the second can collide into a small loop, but those are astronomically rare.

> Sha256 is used for randomness all the time.

I think you are confused about entropy vs randomness.

**Comment by firepacket** [comment]
Hey!
Thanks a lot for getting back to me on this. I will study what you've done and what you're saying.
Thanks again!
